version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 8SRU5rprnjqETJmk
      POSTGRES_DB: NTUSport
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_PASSWORD: 8SRU5rprnjqETJmk
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
