# Generated by Django 2.1.5 on 2019-01-11 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='manager',
            new_name='managers',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_team', related_query_name='lead_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='vice_caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_lead_team', related_query_name='vice_lead_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
