# Generated by Django 2.1.5 on 2019-01-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190111_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_team', related_query_name='lead_team', to='player.Student'),
        ),
        migrations.AlterField(
            model_name='team',
            name='managers',
            field=models.ManyToManyField(related_name='manage_team', related_query_name='vice_leading_team', to='player.Student'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='player.Student'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vice_caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_lead_team', related_query_name='vice_lead_team', to='player.Student'),
        ),
    ]
