# Generated by Django 2.1.5 on 2019-01-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('referees', models.ManyToManyField(to='player.Student')),
                ('teams', models.ManyToManyField(through='schedule.Competition', to='team.Team')),
                ('win', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_schedule', related_query_name='win_schedule', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN', models.PositiveSmallIntegerField(default=0, verbose_name='minutes')),
                ('PTS', models.PositiveSmallIntegerField(default=0, verbose_name='points')),
                ('FGA', models.PositiveSmallIntegerField(default=0, verbose_name='field goal attempts')),
                ('FGM', models.PositiveSmallIntegerField(default=0, verbose_name='field goal made')),
                ('three_PA', models.PositiveSmallIntegerField(default=0, verbose_name='3-pointer attempts')),
                ('three_PM', models.PositiveSmallIntegerField(default=0, verbose_name='3-pointer made')),
                ('FTA', models.PositiveSmallIntegerField(default=0, verbose_name='free throw attempts')),
                ('FTM', models.PositiveSmallIntegerField(default=0, verbose_name='free throw made')),
                ('OR', models.PositiveSmallIntegerField(default=0, verbose_name='offensive rebounds')),
                ('DR', models.PositiveSmallIntegerField(default=0, verbose_name='defensive rebounds')),
                ('BS', models.PositiveSmallIntegerField(default=0, verbose_name='block shoots')),
                ('AST', models.PositiveSmallIntegerField(default=0, verbose_name='assists')),
                ('BLK', models.PositiveSmallIntegerField(default=0, verbose_name='blocks')),
                ('STL', models.PositiveSmallIntegerField(default=0, verbose_name='steals')),
                ('TO', models.PositiveSmallIntegerField(default=0, verbose_name='turnovers')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Student')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(through='schedule.Statistic', to='player.Student'),
        ),
        migrations.AddField(
            model_name='competition',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='competition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
