# Generated by Django 2.1.5 on 2019-01-11 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN', models.PositiveSmallIntegerField(verbose_name='minutes')),
                ('PTS', models.PositiveSmallIntegerField(verbose_name='points')),
                ('FGA', models.PositiveSmallIntegerField(verbose_name='field goal attempts')),
                ('FGM', models.PositiveSmallIntegerField(verbose_name='field goal made')),
                ('three_PA', models.PositiveSmallIntegerField(verbose_name='3-pointer attempts')),
                ('three_PM', models.PositiveSmallIntegerField(verbose_name='3-pointer made')),
                ('FTA', models.PositiveSmallIntegerField(verbose_name='free throw attempts')),
                ('FTM', models.PositiveSmallIntegerField(verbose_name='free throw made')),
                ('OR', models.PositiveSmallIntegerField(verbose_name='offensive rebounds')),
                ('DR', models.PositiveSmallIntegerField(verbose_name='defensive rebounds')),
                ('BS', models.PositiveSmallIntegerField(verbose_name='block shoots')),
                ('AST', models.PositiveSmallIntegerField(verbose_name='assists')),
                ('BLK', models.PositiveSmallIntegerField(verbose_name='blocks')),
                ('STL', models.PositiveSmallIntegerField(verbose_name='steals')),
                ('TO', models.PositiveSmallIntegerField(verbose_name='turnovers')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(through='schedule.Play', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
            ],
        ),
    ]
