# Generated by Django 2.1.5 on 2019-01-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('schedule', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teams',
            field=models.ManyToManyField(through='schedule.Competition', to='team.Team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(through='schedule.Statistic', to='player.Student'),
        ),
        migrations.AddField(
            model_name='competition',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='competition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
