# Generated by Django 2.1.5 on 2019-01-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('schedule', '0002_auto_20190112_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win', related_query_name='win', to='team.Team'),
        ),
    ]
