# Generated by Django 2.1.5 on 2019-01-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190111_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='referees',
            field=models.ManyToManyField(to='player.Student'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='players',
            field=models.ManyToManyField(through='schedule.Play', to='player.Student'),
        ),
    ]
