# Generated by Django 2.1.5 on 2019-01-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190111_0641'),
        ('team', '0003_auto_20190111_0641'),
        ('schedule', '0003_auto_20190111_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='play',
            name='player',
        ),
        migrations.RemoveField(
            model_name='play',
            name='statistic',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='players',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='team',
        ),
        migrations.AddField(
            model_name='statistic',
            name='AST',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='assists'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='BLK',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='blocks'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='BS',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='block shoots'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='DR',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='defensive rebounds'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='FGA',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='field goal attempts'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='FGM',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='field goal made'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='FTA',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='free throw attempts'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='FTM',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='free throw made'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='MIN',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='minutes'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='OR',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='offensive rebounds'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='PTS',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='points'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='STL',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='steals'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='TO',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='turnovers'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='three_PA',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='3-pointer attempts'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='three_PM',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='3-pointer made'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teams',
            field=models.ManyToManyField(through='schedule.Competition', to='team.Team'),
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.AddField(
            model_name='competition',
            name='players',
            field=models.ManyToManyField(through='schedule.Statistic', to='player.Student'),
        ),
        migrations.AddField(
            model_name='competition',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='competition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Competition'),
        ),
    ]
